# Generated by Django 4.0.3 on 2022-03-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='createComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('complaint_text', models.TextField(max_length=5000)),
                ('reviewer', models.CharField(blank=True, max_length=300, null=True)),
                ('against', models.CharField(blank=True, max_length=300, null=True)),
                ('proof', models.ImageField(upload_to='complaint_proof/')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In progress', 'In progress'), ('Reviewed', 'Reviewed'), ('Declined', 'Declined')], default='Declined', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
