# Generated by Django 4.0.3 on 2022-03-23 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_name_customuser_phone_customuser_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_adminEmployee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_helpingStaff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_systemAdmin',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student'), ('Administrator', 'Administrator'), ('Staff', 'Staff')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
