# Generated by Django 4.0.2 on 2022-03-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student'), ('Administrator', 'Administrator'), ('Staff', 'Staff')], max_length=100),
        ),
    ]
