# Generated by Django 4.0.2 on 2022-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Sign up as', 'Sign up as'), ('Faculty', 'Faculty'), ('Student', 'Student'), ('Administrator', 'Administrator'), ('Staff', 'Staff')], default='Sign up as', max_length=100),
        ),
    ]
