# Generated by Django 4.0.2 on 2022-03-26 21:19

import Authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_alter_customuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nsu_id',
            field=models.CharField(max_length=10, unique=True, validators=[Authentication.validators.validate_id]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[Authentication.validators.validate_phone]),
        ),
    ]
