# Generated by Django 4.0.2 on 2022-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0010_reviewer_nonreviewer_helpingstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
        migrations.AddField(
            model_name='adminemployee',
            name='picture',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='picture',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='helpingstaff',
            name='picture',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='dp/default.png', null=True, upload_to='dp/'),
        ),
    ]
