# Generated by Django 4.0.3 on 2022-04-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_remove_customuser_picture_adminemployee_picture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminEmployee',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='HelpingStaff',
            new_name='Staff',
        ),
    ]
