# Generated by Django 4.0.3 on 2022-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint', '0004_alter_complaints_against_alter_complaints_reviewer_and_more'),
        ('Authentication', '0012_rename_adminemployee_administrator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='user',
        ),
        migrations.DeleteModel(
            name='NonReviewer',
        ),
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
